version: "3.9"

services:
  common:
    build:
      context: ${COMMON_DIR:-.}
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: carla
        PLATFORM: ${PLATFORM:-nvidia}
    image: ${IMAGES_NAMESPACE:-wielgoszinfo}/carla-common:${PLATFORM:-nvidia}-latest
